# Generated by Django 4.0.6 on 2022-07-27 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('height', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('BMI', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('patient_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visits', to='patients.patient')),
            ],
        ),
    ]
