# Generated by Django 3.2.14 on 2022-07-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='patient_details',
            new_name='patient_id',
        ),
    ]
