# Generated by Django 3.2.14 on 2022-08-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_rename_patient_id_visit_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_health_status', models.CharField(max_length=10)),
                ('health_question', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=255)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.visit')),
            ],
        ),
    ]
