branch-defaults:
  main:
    environment: SimpleWebApp-env
environment-defaults:
  SimpleWebApp-env:
    branch: null
    repository: null
global:
  application_name: SimpleWebApp
  default_ec2_keyname: rl-private-subnet
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
